<?xml version = "1.0" encoding = "UTF-8"?>

<!DOCTYPE note[

  <!ELEMENT note (to,from,heading,body)>
  <!ELEMENT to (#PCDATA)>
  <!ELEMENT from (#PCDATA)>
  <!ELEMENT heading (#PCDATA)>
  <!ELEMENT body (#PCDATA)>

]>

<note>
  <to>John</to>
  <from>Dhanush</from>
  <heading>Reminder</heading>
  <body>We will plan a trip</body>
</note>